USE DIPE;
-- CALL account_add("moc-admin", "123", "user"); 
-- CALL user_activation("0fe78267-a6c1-11ed-bda0-70b5e82054d1", "1")
-- CALL user_change_password("0fe78267-a6c1-11ed-bda0-70b5e82054d1", "mat khau moi ne")
-- CALL user_change_info("940180ee-a69e-11ed-bda0-70b5e82054d1", "Bành Thị Mộng Mèo", "btm.meo@gmail.com", "0368474601", "Space Station 03 .Nova. Mars")
-- CALL user_login("moc-admin", "13");
-- CALL table_add("KHÁCH HÀNG NHE QUÍ DỊ", "alias_01021") ;
-- CALL table_modify(2, "Sẻn phửm")
-- CALL `add_field`(1, "Mã sản phẩm", "MASP_ALIAS", FALSE, "INT", '{"AUTO_INCREMENT": "TRUE" }', "", TRUE );
-- CALL `add_field`(1, "Tên sản phẩm", "TENSP_ALIAS", TRUE, "VARCHAR", '{"LENGTH": "255" }', "", False );
-- CALL `add_field`(1, "Đơn vị đến", "DVD", FALSE, "VARCHAR", '{"LENGTH": "255" }', "Bao", False );
-- CALL `add_field`(1, "Nhà sản xuất", "NSX", FALSE, "INT", NULL, "", False ); 
-- CALL `modify_field`( 9, "MASP",  TRUE,  "VARCHAR", '{"length": "255"}', "", TRUE );