export default {
    css: [
        { id: 0, prop: "color", inputType: "color", defaultValue: "#000" },
        { id: 1, prop: "width", inputType: "text", defaultValue: null },
        { id: 2, prop: "display", inputType: "dropbox", defaultValue: [ "block", "flex", "inline", "inline-block", "table-cell" ] },
        { id: 4, prop: "magrin", inputType: "number", defaultValue: "0" },
        { id: 5, prop: "magrinTop", inputType: "text", defaultValue: "0" },
        { id: 6, prop: "magrinRight", inputType: "text", defaultValue: "0" },
        { id: 7, prop: "magrinBottom", inputType: "text", defaultValue: "0" },
        { id: 8, prop: "magrinLeft", inputType: "text", defaultValue: "0" },
        { id: 9, prop: "padding", inputType: "text", defaultValue: "0" },
        { id: 10, prop: "paddingTop", inputType: "text", defaultValue: "0" },
        { id: 11, prop: "paddingRight", inputType: "text", defaultValue: "0" },
        { id: 12, prop: "paddingBottom", inputType: "text", defaultValue: "0" },
        { id: 13, prop: "paddingLeft", inputType: "text", defaultValue: "0" },
        { id: 14, prop: "border-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 15, prop: "border-width", inputType: "nummber", defaultValue: "0" },
        { id: 16, prop: "border-color", inputType: "nummber", defaultValue: "0" },
        { id: 17, prop: "border-top-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 18, prop: "border-right-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 19, prop: "border-bottom-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 20, prop: "border-left-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 21, prop: "height", inputType: "nummber", defaultValue: "0" },
        { id: 22, prop: "max-height", inputType: "nummber", defaultValue: "0" },
        { id: 23, prop: "max-width", inputType: "nummber", defaultValue: "0"},
        { id: 24, prop: "outline-style", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 25, prop: "outline-color", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 26, prop: "outline-width", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 27, prop: "outline-offset", inputType: "dropbox", defaultValue: [ "none","solid","dashed","dotted" ] },
        { id: 29, prop: "font-style", inputType: "dropbox", defaultValue: [ "normal","italic","oblique" ] },
        { id: 30, prop: "font-weight", inputType: "dropbox", defaultValue: [ "normal","bold"] },
        { id: 31, prop: "font-variant", inputType: "dropbox", defaultValue: [ "normal","small-caps"] },
        { id: 32, prop: "font-size", inputType: "number", defaultValue: "10" },
        { id: 33, prop: "border-collapse", inputType: "text", defaultValue: "collapse" },
        { id: 35, prop: "text-align", inputType: "dropbox", defaultValue: [ "left", "right","center","justify" ] },
        { id: 34, prop: "vertical-align", inputType: "dropbox", defaultValue: [ "top", "bottom","center"] },
        { id: 36, prop: "position", inputType: "dropbox", defaultValue: [ "static", "relative","fixed","absolute","sticky" ] },
        { id: 37, prop: "z-index", inputType: "number", defaultValue: "1"},
        { id: 38, prop: "top", inputType: "number", defaultValue: "0"},
        { id: 39, prop: "bottom", inputType: "number", defaultValue: "0" },
        { id: 40, prop: "left", inputType: "number", defaultValue: "0" },
        { id: 41, prop: "right", inputType: "number", defaultValue: "0" },
        { id: 42, prop: "overflow", inputType: "dropbox", defaultValue: [ "visible ", "hidden ","scroll ","auto " ] },
        { id: 43, prop: "opacity:", inputType: "text", defaultValue:  "1"},
        { id: 44, prop: "border-radius", inputType: "number", defaultValue: "0" },
    ]
}
